notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#sayit"
    use_notice: true

language: python

services:
  - elasticsearch

env:
  - SELENIUM_TESTS=1 MODULES="Django>=1.4,<1.5"
  - SELENIUM_TESTS=1 MODULES="Django>=1.5,<1.6"
  - SELENIUM_TESTS=1 MODULES="Django>=1.6,<1.7"
#  - SELENIUM_TESTS=1 MODULES="git+https://github.com/django/django.git@master#egg=django"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg libavcodec-extra-53 iceweasel xvfb yui-compressor
  - gem install --conservative --no-ri --no-rdoc sass -v 3.2.14
  - gem install --conservative --no-ri --no-rdoc compass -v 0.12.2
  - gem install --conservative --no-ri --no-rdoc zurb-foundation -v 4.3.2
  - pip install $MODULES
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database "sayit-example-project";' -U postgres
  - ./manage.py syncdb --noinput --migrate
  - ./manage.py collectstatic --noinput
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - ./manage.py test
